// <auto-generated />
using System;
using Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.Content.Achievments.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Description");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("IconPath");

                    b.Property<bool>("IsCourseRelated")
                        .HasColumnType("bit")
                        .HasColumnName("IsCourseRelated");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int")
                        .HasColumnName("Target_Value");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Achievement", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.CourseContent.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("Cost");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("Опис ще не написаний")
                        .HasColumnName("Description");

                    b.Property<string>("ImgPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Icon_path");

                    b.Property<bool>("InDevelopment")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int")
                        .HasColumnName("Language");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Course", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.CourseWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("DictionaryId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("DictionaryId");

                    b.ToTable("CourseWord", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.DictionaryContent.MyDictionary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("Language");

                    b.Property<int>("LanguageLevel")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("LanguageLevel");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Word");

                    b.HasKey("Id");

                    b.ToTable("Dictionary", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.GrammarContent.Grammar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Grammar", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.CourseModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("CourseId");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_available");

                    b.Property<string>("PathToMap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Path_to_map");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Course_Module", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseModuleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Is_available");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CourseModuleId");

                    b.ToTable("Lesson", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.LessonQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AudioQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int?>("SimpleQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("TextQuestionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AudioQuestionId");

                    b.HasIndex("ImageQuestionId");

                    b.HasIndex("LessonId");

                    b.HasIndex("SimpleQuestionId");

                    b.HasIndex("TextQuestionId");

                    b.ToTable("Lesson_question", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.Theory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image_path");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text_content");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<string>("_serializedListContent")
                        .HasColumnType("text")
                        .HasColumnName("ListContent");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Theory", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.Answer.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AudioQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Option");

                    b.Property<int?>("SimpleQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("TextQuestionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("AudioQuestionId");

                    b.HasIndex("ImageQuestionId");

                    b.HasIndex("SimpleQuestionId");

                    b.HasIndex("TextQuestionId");

                    b.ToTable("AnswerOption", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.Answer.RightAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("AudioQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("ImageQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SimpleQuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("TextQuestionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("AudioQuestionId");

                    b.HasIndex("ImageQuestionId");

                    b.HasIndex("SimpleQuestionId");

                    b.HasIndex("TextQuestionId");

                    b.ToTable("RightAnswers", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.AudioQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AType")
                        .HasColumnType("int")
                        .HasColumnName("AnswerType");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Audio_path");

                    b.Property<int>("QType")
                        .HasColumnType("int")
                        .HasColumnName("QuestionType");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("QuestionText");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Audio_Question", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.PictureQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AType")
                        .HasColumnType("int")
                        .HasColumnName("AnswerType");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image_path");

                    b.Property<int>("QType")
                        .HasColumnType("int")
                        .HasColumnName("QuestionType");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("QuestionText");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Picture_Question", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.SimpleQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AType")
                        .HasColumnType("int")
                        .HasColumnName("AnswerType");

                    b.Property<int>("QType")
                        .HasColumnType("int")
                        .HasColumnName("QuestionType");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("QuestionText");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Simple_Question", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.TextQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AType")
                        .HasColumnType("int")
                        .HasColumnName("AnswerType");

                    b.Property<int>("QType")
                        .HasColumnType("int")
                        .HasColumnName("QuestionType");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("QuestionText");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text_with_question");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Text_Question", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.Content.StoryContent.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Story", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.User.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("NativeLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserIcon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.User.UserProfile.UserSociable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Icon Path");

                    b.Property<string>("Link")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasDefaultValue("")
                        .HasColumnName("Link");

                    b.Property<int>("Sociable")
                        .HasColumnType("int")
                        .HasColumnName("Sociable");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSociable", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.TaskResult.UserGrammarResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrammarId")
                        .HasColumnType("int")
                        .HasColumnName("GrammarId");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GrammarId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGrammarResult", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.TaskResult.UserLessonResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("LessonId");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLessonResult", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.TaskResult.UserStoryResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<int>("StoryId")
                        .HasColumnType("int")
                        .HasColumnName("StoryId");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStoryResult", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEarned")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateEarned");

                    b.Property<bool>("IsEarned")
                        .HasColumnType("bit")
                        .HasColumnName("IsEarned");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievement", "dbo");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.UserWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateAdded");

                    b.Property<int>("DictionaryId")
                        .HasColumnType("int")
                        .HasColumnName("DictionaryId");

                    b.Property<bool>("IsLearned")
                        .HasColumnType("bit")
                        .HasColumnName("IsLearned");

                    b.Property<DateTime?>("LastReviewed")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastReviewed");

                    b.Property<int>("RepetitionCount")
                        .HasColumnType("int")
                        .HasColumnName("RepetitionCount");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DictionaryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserWord", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Content.Achievments.Achievement", b =>
                {
                    b.HasOne("Domain.Entity.Content.CourseContent.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entity.Content.CourseWord", b =>
                {
                    b.HasOne("Domain.Entity.Content.CourseContent.Course", "Course")
                        .WithMany("CourseWords")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.Content.DictionaryContent.MyDictionary", "Dictionary")
                        .WithMany("CourseWords")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Dictionary");
                });

            modelBuilder.Entity("Domain.Entity.Content.GrammarContent.Grammar", b =>
                {
                    b.HasOne("Domain.Entity.Content.CourseContent.Course", "Course")
                        .WithMany("Grammars")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.CourseModule", b =>
                {
                    b.HasOne("Domain.Entity.Content.CourseContent.Course", "Course")
                        .WithMany("CourseModules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Course_CourseId_CourseModules");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.Lesson", b =>
                {
                    b.HasOne("Domain.Entity.Content.Lessons.CourseModule", "CourseModules")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CourseModules_.ModuleLessonsId_Lessons");

                    b.Navigation("CourseModules");
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.LessonQuestion", b =>
                {
                    b.HasOne("Domain.Entity.Content.Question.AudioQuestion", "AudioQuestion")
                        .WithMany("LessonQuestions")
                        .HasForeignKey("AudioQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LessonQuestions_AudioQuestionId_AudioQuestion");

                    b.HasOne("Domain.Entity.Content.Question.PictureQuestion", "ImageQuestion")
                        .WithMany("LessonQuestions")
                        .HasForeignKey("ImageQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LessonQuestions_ImageQuestionId_ImageQuestion");

                    b.HasOne("Domain.Entity.Content.Lessons.Lesson", "Lesson")
                        .WithMany("LessonQuestions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LessonQuestions_LessonId_Lesson");

                    b.HasOne("Domain.Entity.Content.Question.SimpleQuestion", "SimpleQuestion")
                        .WithMany("LessonQuestions")
                        .HasForeignKey("SimpleQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LessonQuestions_SimpleQuestionId_SimpleQuestion");

                    b.HasOne("Domain.Entity.Content.Question.TextQuestion", "TextQuestion")
                        .WithMany("LessonQuestions")
                        .HasForeignKey("TextQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LessonQuestions_TextQuestionId_TextQuestion");

                    b.Navigation("AudioQuestion");

                    b.Navigation("ImageQuestion");

                    b.Navigation("Lesson");

                    b.Navigation("SimpleQuestion");

                    b.Navigation("TextQuestion");
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.Theory", b =>
                {
                    b.HasOne("Domain.Entity.Content.Lessons.Lesson", "Lesson")
                        .WithMany("TheoryBlock")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lesson_LessonId_LectureBlock");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.Answer.AnswerOption", b =>
                {
                    b.HasOne("Domain.Entity.Content.Question.AudioQuestion", "AudioQuestion")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("AudioQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entity.Content.Question.PictureQuestion", "ImageQuestion")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("ImageQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entity.Content.Question.SimpleQuestion", "SimpleQuestion")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("SimpleQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entity.Content.Question.TextQuestion", "TextQuestion")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("TextQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AudioQuestion");

                    b.Navigation("ImageQuestion");

                    b.Navigation("SimpleQuestion");

                    b.Navigation("TextQuestion");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.Answer.RightAnswer", b =>
                {
                    b.HasOne("Domain.Entity.Content.Question.AudioQuestion", "AudioQuestion")
                        .WithMany("RightAnswers")
                        .HasForeignKey("AudioQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entity.Content.Question.PictureQuestion", "ImageQuestion")
                        .WithMany("RightAnswers")
                        .HasForeignKey("ImageQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entity.Content.Question.SimpleQuestion", "SimpleQuestion")
                        .WithMany("RightAnswers")
                        .HasForeignKey("SimpleQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entity.Content.Question.TextQuestion", "TextQuestion")
                        .WithMany("RightAnswers")
                        .HasForeignKey("TextQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AudioQuestion");

                    b.Navigation("ImageQuestion");

                    b.Navigation("SimpleQuestion");

                    b.Navigation("TextQuestion");
                });

            modelBuilder.Entity("Domain.Entity.Content.StoryContent.Story", b =>
                {
                    b.HasOne("Domain.Entity.Content.CourseContent.Course", "Course")
                        .WithMany("Stories")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProfile.UserSociable", b =>
                {
                    b.HasOne("Domain.Entity.User.User", "User")
                        .WithMany("UserSociables")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.TaskResult.UserGrammarResult", b =>
                {
                    b.HasOne("Domain.Entity.Content.GrammarContent.Grammar", "Grammar")
                        .WithMany("GrammarResults")
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.User.User", "User")
                        .WithMany("GrammarResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.TaskResult.UserLessonResult", b =>
                {
                    b.HasOne("Domain.Entity.Content.Lessons.Lesson", "Lesson")
                        .WithMany("UserLessonsResult")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.User.User", "User")
                        .WithMany("LessonResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.TaskResult.UserStoryResult", b =>
                {
                    b.HasOne("Domain.Entity.Content.StoryContent.Story", "Story")
                        .WithMany("StoryResults")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.User.User", "User")
                        .WithMany("StoryResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.UserAchievement", b =>
                {
                    b.HasOne("Domain.Entity.Content.Achievments.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.User.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.User.UserProgress.UserWord", b =>
                {
                    b.HasOne("Domain.Entity.Content.DictionaryContent.MyDictionary", "Dictionary")
                        .WithMany("UserWords")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.User.User", "User")
                        .WithMany("UserWords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dictionary");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entity.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entity.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entity.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entity.User.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entity.Content.Achievments.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("Domain.Entity.Content.CourseContent.Course", b =>
                {
                    b.Navigation("CourseModules");

                    b.Navigation("CourseWords");

                    b.Navigation("Grammars");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("Domain.Entity.Content.DictionaryContent.MyDictionary", b =>
                {
                    b.Navigation("CourseWords");

                    b.Navigation("UserWords");
                });

            modelBuilder.Entity("Domain.Entity.Content.GrammarContent.Grammar", b =>
                {
                    b.Navigation("GrammarResults");
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.CourseModule", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Domain.Entity.Content.Lessons.Lesson", b =>
                {
                    b.Navigation("LessonQuestions");

                    b.Navigation("TheoryBlock");

                    b.Navigation("UserLessonsResult");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.AudioQuestion", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("LessonQuestions");

                    b.Navigation("RightAnswers");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.PictureQuestion", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("LessonQuestions");

                    b.Navigation("RightAnswers");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.SimpleQuestion", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("LessonQuestions");

                    b.Navigation("RightAnswers");
                });

            modelBuilder.Entity("Domain.Entity.Content.Question.TextQuestion", b =>
                {
                    b.Navigation("AnswerOptions");

                    b.Navigation("LessonQuestions");

                    b.Navigation("RightAnswers");
                });

            modelBuilder.Entity("Domain.Entity.Content.StoryContent.Story", b =>
                {
                    b.Navigation("StoryResults");
                });

            modelBuilder.Entity("Domain.Entity.User.User", b =>
                {
                    b.Navigation("GrammarResults");

                    b.Navigation("LessonResults");

                    b.Navigation("StoryResults");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserSociables");

                    b.Navigation("UserWords");
                });
#pragma warning restore 612, 618
        }
    }
}
